// Error codes shared with backend.
export const CREATE_WALLET_ERROR_CODE = {
	WALLET_NAME_TOO_LONG: "WALLET_NAME_TOO_LONG",
	WALLET_TYPE_REQUIRED: "WALLET_TYPE_REQUIRED",
	INVALID_WALLET_TYPE: "INVALID_WALLET_TYPE",
	CURRENCY_TYPE_REQUIRED: "CURRENCY_TYPE_REQUIRED",
	INVALID_CURRENCY_TYPE: "INVALID_CURRENCY_TYPE",
} as const;

export type CreateWalletErrorCode =
	(typeof CREATE_WALLET_ERROR_CODE)[keyof typeof CREATE_WALLET_ERROR_CODE];
