// Error codes shared with backend.
export const LOGIN_ERROR_CODE = {
	EMAIL_REQUIRED: "EMAIL_REQUIRED",
	INVALID_EMAIL: "INVALID_EMAIL",
	EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
	PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
	PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export type LoginErrorCode =
	(typeof LOGIN_ERROR_CODE)[keyof typeof LOGIN_ERROR_CODE];

// Backend codes + client-only codes for confirm password.
export const REGISTER_ERROR_CODE = {
	EMAIL_REQUIRED: "EMAIL_REQUIRED",
	INVALID_EMAIL: "INVALID_EMAIL",
	EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
	PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
	PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
	PASSWORD_REQUIRES_DIGIT: "PASSWORD_REQUIRES_DIGIT",
	PASSWORD_REQUIRES_LOWERCASE: "PASSWORD_REQUIRES_LOWERCASE",
	PASSWORD_REQUIRES_UPPERCASE: "PASSWORD_REQUIRES_UPPERCASE",
	FIRST_NAME_REQUIRED: "FIRST_NAME_REQUIRED",
	FIRST_NAME_TOO_SHORT: "FIRST_NAME_TOO_SHORT",
	FIRST_NAME_TOO_LONG: "FIRST_NAME_TOO_LONG",
	LAST_NAME_REQUIRED: "LAST_NAME_REQUIRED",
	LAST_NAME_TOO_SHORT: "LAST_NAME_TOO_SHORT",
	LAST_NAME_TOO_LONG: "LAST_NAME_TOO_LONG",
	PASSWORD_CONFIRM_REQUIRED: "PASSWORD_CONFIRM_REQUIRED",
	PASSWORD_CONFIRM_MISMATCH: "PASSWORD_CONFIRM_MISMATCH",
	REGISTRATION_FAILED: "REGISTRATION_FAILED",
} as const;

export type RegisterErrorCode =
	(typeof REGISTER_ERROR_CODE)[keyof typeof REGISTER_ERROR_CODE];
